# This is the default configuration
baseURL = "https://texasbutterfliesmonitoring.org/"
languageCode = "en-us"
title = "Texas Butterfly Monitoring Network"
copyright = """Copyright Â© 2021 Texas Butterfly Monitoring Network"""
disableKinds = [
    "taxonomy",
    "term",
    "section",
    "RSS",
]
publishDir = "generated_website"
pathWarnings = true
[markup]
  [markup.tableOfContents]
    ordered = true
